
name: api-test-pipeline
on:
  push:
    paths: [api/*]
env:
  ENVIRONMENT: dev
  PROJECT_ID: rules-engine-dev-393220
  REGION: europe-west1
  SERVICE_NAME: atlantechapi
  WORKING_DIRECTORY: api
jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    # Downloads a copy of the code in your repository before running CI tests
    - name: Checkout
      uses: actions/checkout@v2
    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ env.PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_DEV_SERVICE_ACCOUNT }}
    - name: Set up Python 3.13
      uses: actions/setup-python@v1
      with:
        python-version: 3.13
        cache: 'pip' # caching pip dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Run unit tests
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        python -m pytest test_app.py -v
